apiVersion: v1
kind: Service
metadata:
  name: {{ include "moksha-mint.fullname" . }}
  labels: {{- include "moksha-mint.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector: {{- include "moksha-mint.selectorLabels" . | nindent 4 }}
